### ISSUE TITLE
Improve contributing for the community

### ISSUE THREAD

**Issue by gregk-git** [prrvchr/oneDriveOOo#2]
It would be good to have a contributing section in readme.md to detail how best to contribute, perhaps even a table of contents (installing, contributing)
It would also be great if you set up the milestones/Projects, so that we can see what bugs and functionality is on the "to do".
Would also be good to setup issues for each feature, and for them to be tagged as a feature, and also tagged "needs help".

With all of that completed, contributors will know:
* What features are needed
* Where can we help
* be able to "vote" on features they want/view as a priority by using an emoji 👍 or 👎 

This will significantly help the community to contribute.

Also, as a side note: a lot of the FOSS community doesn't like GitHub because Microsoft purchased it, many moved to GitLab, though that probably won't bother many for this project, because it's literally for integrating Microsoft's OneDrive service. It personally doesn't bother me, but perhaps it would be good to have a GitLab mirror, or perhaps even move to GitLab and maintain this as a mirror?

**Comment by prrvchr** [comment]
Hi gregk-git,

> It would be good to have a contributing section in readme.md to detail how best to contribute...
it's a good idea, I'm ready to integrate all new README.md bringing this type of feature. You have to make a pull request...

> Also, as a side note: a lot of the FOSS community doesn't like GitHub because Microsoft purchased it...
why not, but we need the possibility of having a dedicated domain (like: https://prrvchr.github.io/OAuth2OOo/) this is necessary for the registration of OAuth2OOo with some suppliers (Google, Microsoft ...), and I must also say that I use [SubRepo](https://github.com/ingydotnet/git-subrepo) to share python modules between extensions.

If you're ready to do it, then let's go ...

**Comment by prrvchr** [comment]
Hi gregk-git,

Without answer I close ...
