### ISSUE TITLE
opening files leads to "Object does not exist" dialog

### ISSUE THREAD

**Issue by wsourdeau** [prrvchr/oneDriveOOo#3]
Hi, I seem to experience the same issue as reposted in issue #1 . I am using LibreOffice 7.0.4 under Debian Bullseye (sid/testing).

Whenever I try to open a file using the documented procedure, I see this dialog and then nothing happens:
![image](https://user-images.githubusercontent.com/1819745/104652092-9a580c00-5686-11eb-89ef-da2ecc00ad82.png)

Another interesting symptom is that, in the configuration dialog, whenever I click on the "datasource" button, I get a dialog telling me that "vnd.microsoft-apps.odb" does not exist.

Starting LibreOffice from the command line shows nothing interesting:
/* beginning of log */
wolfgang@lgi20q2sblln433:~$ soffice 

(soffice:42791): Gtk-WARNING **: 16:33:49.765: Theme parsing error: gtk.css:4419:85: '/*' in comment block

(soffice:42791): Gtk-WARNING **: 16:33:49.765: Theme parsing error: gtk.css:4512:64: '/*' in comment block

(soffice:42791): Gtk-CRITICAL **: 16:33:53.928: gtk_tree_view_column_set_sort_indicator: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed

(soffice:42791): Gtk-CRITICAL **: 16:33:53.928: gtk_tree_view_column_set_sort_order: assertion 'GTK_IS_TREE_VIEW_COLUMN (tree_column)' failed
         1    42791 2021-01-14 21:34:11.976338058 ContentProviderProxy::__init__(): ContentProviderProxy for plugin: com.gmail.prrvchr.extensions.oneDriveOOo loading ... Done

ContentProviderProxy.__init__()
ContentProviderProxy.registerInstance() Register Scheme/Plugin/Replace: vnd.microsoft-apps/com.gmail.prrvchr.extensions.oneDriveOOo/True ...
         2    42791 2021-01-14 21:34:11.976567263 ContentProviderProxy::registerInstance(): Register Scheme/Plugin/Replace: vnd.microsoft-apps/com.gmail.prrvchr.extensions.oneDriveOOo/True ... Done

ContentProviderProxy.createContentIdentifier()
ContentProviderProxy._getContentProvider()
ContentProviderProxy.createContentProvider()
         3    42791 2021-01-14 21:34:11.982034076 ContentProvider::__init__(): ContentProvider: com.gmail.prrvchr.extensions.oneDriveOOo.ContentProvider Chargement terminé

         4    42791 2021-01-14 21:34:11.982073281 ContentProvider::registerInstance(): Scheme/Plugin: vnd.microsoft-apps/com.gmail.prrvchr.extensions.oneDriveOOo ... Démarré

ContentProviderProxy.createContentIdentifier()
ContentProviderProxy._getContentProvider()
ContentProviderProxy.createContentProvider()
         5    42791 2021-01-14 21:34:24.782538887 ContentProvider::__init__(): ContentProvider: com.gmail.prrvchr.extensions.oneDriveOOo.ContentProvider Chargement terminé

         6    42791 2021-01-14 21:34:24.782765416 ContentProvider::registerInstance(): Scheme/Plugin: vnd.microsoft-apps/com.gmail.prrvchr.extensions.oneDriveOOo ... Démarré

         7    42791 2021-01-14 21:34:24.874686036 ContentProvider::__del__(): com.gmail.prrvchr.extensions.oneDriveOOo.ContentProvider déchargement ... Terminé

ContentProviderProxy.createContentIdentifier()
ContentProviderProxy._getContentProvider()
ContentProviderProxy.createContentProvider()
         8    42791 2021-01-14 21:34:33.802747507 ContentProvider::__init__(): ContentProvider: com.gmail.prrvchr.extensions.oneDriveOOo.ContentProvider Chargement terminé

         9    42791 2021-01-14 21:34:33.802946633 ContentProvider::registerInstance(): Scheme/Plugin: vnd.microsoft-apps/com.gmail.prrvchr.extensions.oneDriveOOo ... Démarré

        10    42791 2021-01-14 21:34:33.869014400 ContentProvider::__del__(): com.gmail.prrvchr.extensions.oneDriveOOo.ContentProvider déchargement ... Terminé

ContentProviderProxy.createContentIdentifier()
ContentProviderProxy._getContentProvider()
ContentProviderProxy.createContentProvider()
        11    42791 2021-01-14 21:35:50.475423598 ContentProvider::__init__(): ContentProvider: com.gmail.prrvchr.extensions.oneDriveOOo.ContentProvider Chargement terminé

        12    42791 2021-01-14 21:35:50.475640885 ContentProvider::registerInstance(): Scheme/Plugin: vnd.microsoft-apps/com.gmail.prrvchr.extensions.oneDriveOOo ... Démarré

        13    42791 2021-01-14 21:35:50.549512864 ContentProvider::__del__(): com.gmail.prrvchr.extensions.oneDriveOOo.ContentProvider déchargement ... Terminé

        14    42791 2021-01-14 21:38:06.734267918 ContentProvider::__del__(): com.gmail.prrvchr.extensions.oneDriveOOo.ContentProvider déchargement ... Terminé

wizardcontroller.py 1
wizardhandler.py 1
oauth2tools.py 1
/home/wolfgang/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu35568q47um2.tmp_/OAuth2OOo.oxt/pythonpath/oauth2/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
requests.__init__.py 1
oauth2tools.py 2
wizardhandler.py 2
wizardcontroller.py 2
wizardserver.py 1
wizardserver.py 2
wizardserver.py 3
request.py 1
request.py 2
request.py 3
request.py 4
OAuth2Service._getSSLVersion() OpenSSL 1.1.1i  8 Dec 2020
OAuth2Service._getSession() 1 OpenSSL 1.1.1i  8 Dec 2020
         1    42791 2021-01-14 21:38:06.841334371 OptionsDialog::__init__(): Loading ... Done

OptionDialog._doConnect() 1
OptionDialog._doConnect() 3  -  - False
OAuth2Service.getAuthorization() 1
Wizard.__init__() 1
Wizard.__init__() 2
Wizard.__init__() 3
Wizard.__init__() 4
Wizard.__init__() 5
Wizard.__init__() 6
OAuth2Service.getAuthorization() 2
WizardController.__init__() 0
OAuth2Service.getAuthorization() 3
OAuth2Service.getAuthorization() 4
OAuth2Service.getAuthorization() 5
Wizard.execute() 1
         2    42791 2021-01-14 21:38:07.933213784 WizardPage::__init__(): PageId: 1 ... Done

         3    42791 2021-01-14 21:38:07.933247188 WizardController::createPage(): PageId: 1 ... Done

         4    42791 2021-01-14 21:38:07.942107992 WizardController::onActivatePage(): PageId: 1... Done

         5    42791 2021-01-14 21:38:07.942139296 WizardPage::activatePage(): PageId: 1 ... Done

Wizard.execute() 2
         6    42791 2021-01-14 21:38:08.537909347 OAuth2Service::getAuthorization(): Wizard Loading ... Done ... ERROR: Wizard as been aborted

OptionDialog._doConnect() 4
PyOptionsDialog.__init__() 1
/* end of log */

**Comment by prrvchr** [comment]
Hi wsourdeau,

Thank you for reporting this issue, it improves the software...

If you are using LibreOffice on Linux, the first thing to do is to uninstall the packages:
- libreoffice-sdbc-hsqldb 
- libhsqldb1.8.0-java

If you still need to use Embedded HsqlDB, then do so by installing [HsqlDBembeddedOOo](https://prrvchr.github.io/HsqlDBembeddedOOo/)

I think this should solve your problem.

Keep me informed

Thank you

**Comment by prrvchr** [comment]
Hi [wsourdeau](https://github.com/wsourdeau),

Thank you for testing, it helps to improve the extensions.

Many changes have been made since this issue was opened, see [issue #5](https://github.com/prrvchr/oneDriveOOo/issues/5)

I'm closing this issue, you'll have to open another one if the problem persists.
