### ISSUE TITLE
curious behavior for oneDriveOOo.oxt

### ISSUE THREAD

**Issue by pfischer27** [prrvchr/oneDriveOOo#4]
Good Day,
     I very much like te work that has been done to allow LibreOffice to access OneDrive.

     I do have some unusual results.

     First,  I am running Raspbian 10 (on Raspberry Pi 4B) and LibreOffice 6.1.5.2

     I have no problem connecting with either 
         vnd.microsoft-apps://your_account/
     or 
         vnd.microsoft-apps:///

     when I get the below window (fig 1)
     I notice a single file missing  (_Sailing summary.xlxs)
     I can open all the folders except "Music" which is definitely not empty
     For Folders that I can open I can access them in LibreOffice Calc or whatever app is appropriate.

     Fig 1

      Also, when i open the Documents folder (fig 2)  I can navigate to  and access folders and files 
      except the _Sailing folder.  It is not empty but i cannot navigate to it.

     Fig 2

    I am wondering if there is a way to refresh the local database for the
    oneDriveOOo.oxt extension?

Thanks for any help.

Peter F
Fig 1
![2021-08-12_14-15](https://user-images.githubusercontent.com/47600357/129250384-cf3fea21-4505-4f06-9dde-521e6870a839.png)

Fig 2
![2021-08-12_14-16](https://user-images.githubusercontent.com/47600357/129250487-b3ea28f8-7d1a-4690-89a6-052ae6b6775d.png)

**Comment by prrvchr** [comment]
Hi [pfischer27](https://github.com/pfischer27),

Thank you for testing, it helps to improve the extensions.

Many changes have been made since this issue was opened, see [issue #5](https://github.com/prrvchr/oneDriveOOo/issues/5)

I'm closing this issue, you'll have to open another one if the problem persists.
