### ISSUE TITLE
Doesn't work on libreoffice 7.3.3.2

### ISSUE THREAD

**Issue by Ludo-code** [prrvchr/oneDriveOOo#6]
Extension is detected, O2auth is good but when i try to acess or open a file it doesn't work.... Have you any workaround or you want more information ?

**Comment by prrvchr** [comment]
Hi Ludo-code,

Thanks to take time to open issue.

Please, could you give me your OS and Java version?

**Comment by Ludo-code** [comment]
Hello, I'm un kubuntu 22.04 lts and according to our documentation I have downloaded packet :

libreoffice-sdbc-hsqldb

libhsqldb1.8.0-java

I don't have downloaded other more only needed dependency by each one.

**Comment by prrvchr** [comment]
` I have downloaded packet : I have downloaded packet :

libreoffice-sdbc-hsqldblibreoffice-sdbc-hsqldb

libhsqldb1.8.0-javalibhsqldb1.8.0-java
`

On the contrary, it is important not to install these two packages.

You must install [jdbcDriverOOo](https://github.com/prrvchr/jdbcDriverOOo/raw/master/source/jdbcDriverOOo/dist/jdbcDriverOOo.oxt) and Java version 11 minimum

**Comment by Ludo-code** [comment]
Oh sorry I have make a mistake when I have read the doc... I will try our solution tomorrow thanks you :)

**Comment by prrvchr** [comment]
` I have downloaded packet : I have downloaded packet :

libreoffice-sdbc-hsqldblibreoffice-sdbc-hsqldb

libhsqldb1.8.0-javalibhsqldb1.8.0-java
`

On the contrary, it is important not to install these two packages.

You must install [jdbcDriverOOo](https://github.com/prrvchr/jdbcDriverOOo/raw/master/source/jdbcDriverOOo/dist/jdbcDriverOOo.oxt) and Java version 11 minimum
