### ISSUE TITLE
"Nonexistent object. Nonexistent File." error when trying to connect.

### ISSUE THREAD

**Issue by glebinski** [prrvchr/oneDriveOOo#7]
Fedora 37, installed all other required extensions and removed the unnecessary packages. I receive that error when "vnd.microsoft-apps://" into the open dialog.

**Comment by glebinski** [comment]
Fixed by downloading the latest version, prev version wasn't working for some reason.

**Comment by prrvchr** [comment]
Hi [glebinski](https://github.com/glebinski),

I don't change the versions with each update (push), I know it's not good to do so and that it requires reinstalling all the extensions with their latest respective updates.
