### ISSUE TITLE
oneDrive not accessible following install

### ISSUE THREAD

**Issue by john-hoddinott** [prrvchr/oneDriveOOo#8]
Hi prrvchr, 

I apologise in advance if I am doing something stupid, but after a couple of hours I am still unable to get this working. 

I have followed the install instructions on my Ubuntu 23.04 build. I was able to complete the OAUTH process to authenticate with my oneDrive account, but oneDrive does not show up in the list of services when I go to the file open dialog. Am I going about this all wrong?

I confirmed that I do not have the ibreoffice-sdbc-hsqldb or libhsqldb1.8.0-java packages, and I installed the python3-cffi package.

LibreOffice install details are:
Version: 7.5.3.2 (X86_64) / LibreOffice Community
Build ID: 50(Build:2)
CPU threads: 8; OS: Linux 6.2; UI render: default; VCL: kf5 (cairo+xcb)
Locale: en-AU (en_AU.UTF-8); UI: en-US
Ubuntu package version: 4:7.5.3-0ubuntu0.23.04.1
Calc: threaded

Java version:
penJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu123.04)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu123.04, mixed mode, sharing)

Any advice gratefully received.

Regards,

John

**Comment by prrvchr** [comment]
Hi John,

I just did a test with oneDriveOOo and for me everything works, I can open a file to modify it and I find the changes on the oneDrive side.

As I made changes recently, the first thing to do is to uninstall and reinstall all extensions to make sure you have the latest versions of extensions.
If that doesn't change anything then I'll give you some things to check...

**Comment by john-hoddinott** [comment]
Hi prrvchr,

Sorry to be so slow getting in replying, been away all week with work.

I have reinstalled all of the extensions with no obvious change in behaviour. When I go to open a file in Libreoffice I get this dialog, and type "vnd-microsoft://my_onedrive_email_address" as shown below, but nothing happens at all when I hit enter.
![Screenshot_20230610_162130](https://github.com/prrvchr/oneDriveOOo/assets/72127022/c7e6caba-3726-49c9-9feb-1dc3b30bedfb)
I was also expecting OneDrive to now appear as an option in the Servers list, but it is not there
![Screenshot_20230610_162738](https://github.com/prrvchr/oneDriveOOo/assets/72127022/f3ae8526-4b4c-4da7-978d-a76570aaab54)
I am not aware of haing done anything odd to my setup that would be causing this, but I guess I have, or missed some step in the setup. Any suggestions gratefully received.

Regards,

John

**Comment by prrvchr** [comment]
Hi John,

Can you try two things: 

1. Try the gDriveOOo extension to see what happens. 
2. Otherwise open a terminal and launch soffice in this terminal this will give access to any error messages

**Comment by john-hoddinott** [comment]
I have added the gDriveOOo extension.

When I type vnd-google://my.username@gmail.com All I get is the following message:
![Screenshot_20230612_163506](https://github.com/prrvchr/oneDriveOOo/assets/72127022/117d76d9-15bb-47c6-8328-dcf330fc4ba6)

I ran soffice from the terminal and had the same message as above, but nothing was reported in the terminal.

And just to confirm I applied the steps you suggest regarding bug 139538, so neither of those packages are installed.

**Comment by prrvchr** [comment]
Hi John,

Well then if you have this message it means that you did not install the [jdbcDriverOOo](https://github.com/prrvchr/jdbcDriverOOo/) extension as claimed in the [installation section](https://prrvchr.github.io/oneDriveOOo/#installation) of the [oneDriveOOo](https://prrvchr.github.io/oneDriveOOo/) extension.

I remind you that it is imperative to install:
[OAuth2OOo](https://github.com/prrvchr/OAuth2OOo/raw/master/OAuth2OOo.oxt)
[jdbcDriverOOo](https://github.com/prrvchr/jdbcDriverOOo/raw/master/jdbcDriverOOo.oxt)

For the oneDriveOOo extension to work.

**Comment by john-hoddinott** [comment]
Prrvchr,

It's reporting as being installed, and I went through and installed in the order suggested.
![Screenshot_20230612_173845](https://github.com/prrvchr/oneDriveOOo/assets/72127022/cbf3e946-7d4e-43d5-9f6f-ba0b802cceee)

I'll delete them all and try a fresh install.

**Comment by prrvchr** [comment]
The version of gDriveOOo is outdated.

I suspect a LibreOffice profile problem. Can you:

1. uninstall all extensions.
2. exit LibreOffice
3. delete the `~/.config/libreoffice` folder, ~ being your home folder (make a backup if necessary)
4. and reinstall the three extensions
